### PR TITLE
Updates for XCode 8 compilation.

### PR DESCRIPTION
**Pull request by bpascazio**
This are required updates for XCode 8 compilation.

### CODE REVIEW

**Comment by Airruk** [comment]
@BaseInfinity - we ready to merge this in?

**Comment by BaseInfinity** [comment]
Ya sure, as long as we tested this. 32k added lines makes this a bit crazy to try and code review so as long as testing is good then we are good with merging this

**Comment by bpascazio** [comment]
Let me push the latest to my master branch then you can merge.

**Comment by bpascazio** [comment]
Ok this is ready to merge @Diakonia7

**Pull request closed without merging**
