### PR TITLE
Localization  only show english guides to english users

### PR DESCRIPTION
**Pull request by BaseInfinity**
This change will return english guides for english users.
International users will see no change.

### CODE REVIEW

**Comment by marczych** [comment]
CR :lock_with_ink_pen:

**Comment by kwiens** [comment]
Could you share a little more detail on how it works?

I expect the app to pass the langid to the API and display any guides that the API returns.

I'd expect the API to be a bit smart, and display their language content where available, falling back to the source document language if a translation is not available.

**Comment by marczych** [comment]
> I expect the app to pass the langid to the API and display any guides that the API returns.

That's precisely what's happening: `https://%@/api/2.0/wikis/CATEGORY/%@?langid=%@`

> I'd expect the API to be a bit smart, and display their language content where available, falling back to the source document language if a translation is not available.

I'm not sure of the exact behavior, but you have the general idea of what the API should do. See the referenced pull for the API changes.

**Comment by kwiens** [comment]
Is there a parent issue? Difficulty scope this, please!

**Pull request merged**
